### PR TITLE
Fix persistence of persons assigned to project

### LINKED ISSUE #121: Fix persistence of persons assigned to project

### PR DESCRIPTION
**Pull request by ongyixin**
Fixes #121

### CODE REVIEW

File: src/main/java/loopin/projectbook/storage/JsonSerializableProjectBook.java [hunk 1]
```diff
@@ -69,6 +74,23 @@ public ProjectBook toModelType() throws IllegalValueException {
...
+            Project project = projectsByName.get(jsonAdaptedProject.getName());
+            if (project == null) {
+                continue;
+            }
+            for (String email : jsonAdaptedProject.getMembers()) {
+                Person p = personsByEmail.get(email);
+                if (p != null) {
+                    if (!project.hasMember(p)) {
+                        project.assignPerson(p);
+                    }
```
Comment (naa-siuuuu-ff) [inline src/main/java/loopin/projectbook/storage/JsonSerializableProjectBook.java]: Good nullcheck, but it is interesting that you are using email instead of name, what if email is null?
